language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - image="centos-ansible:latest"

script:
  - docker build -t . "$image"
  - docker run -it --rm sendxmpp --help

after_script:
  - docker images

# vim:set et ts=2 sw=2:i
